# Generated by Django 5.2.6 on 2025-09-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
