# Generated by Django 5.2.6 on 2025-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_ip_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_log',
            name='log_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
